---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificate-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mayanklbg/argo-spike.git
    targetRevision: HEAD
    path: adons/certificate-manager
    # helm:
    #   valueFiles:
    #   - '{{filepath}}'
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
