---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manage-namespaces-value-stream2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mayanklbg/argo-spike.git
    targetRevision: HEAD
    path: value-stream2
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
