---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/mayanklbg/argo-spike.git
    targetRevision: HEAD
    path: adons/ingress-nginx
    # helm:
    #   valueFiles:
    #   - '{{filepath}}'
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
