apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvpn-as.fullname" . }}-admin
  labels:
    {{- include "openvpn-as.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.admin.type }}
  ports:
    - port: {{ .Values.openvpn.ports.admin }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "openvpn-as.selectorLabels" . | nindent 4 }}
