apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvpn-as.fullname" . }}-gui
  labels:
    {{- include "openvpn-as.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.gui.type }}
  ports:
    - port: {{ .Values.openvpn.ports.gui }}
      targetPort: gui
      protocol: TCP
      name: gui
  selector:
    {{- include "openvpn-as.selectorLabels" . | nindent 4 }}
