# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: digicert
# spec:
#   acme:
#     email: mayank.agarwal@e.lloydsbanking.com
#     server: <digicert_acmeurl>
#     privateKeySecretRef:
#       name: digicert-key
#     solvers:
#     - dns01:
#         clouddns:
#           project: <project_id>

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Staging API
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: mayank.agarwal@lloydsbanking.com
    privateKeySecretRef:
      name: account-key-staging
    solvers:
    - http01:
        ingress:
          class: nginx
---
