bases:
- ../base

patches:
- target:
    kind: LimitRange
    name: limit-range
  patch: |-
    - op: replace
      path: /metadata/name
      value: limit-kustomize-vals1
    - op: replace
      path: /spec/limits/0/defaultRequest/cpu
      value: 250m
